language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - DB=agnostic                                   #only database agnostic tests
  - DB=mysql DB_USER=root                         #only database tests against mysql
  - DB=pgsql DB_USER=postgres DB_NAME=postgres    #only database tests against postgresql
  - DB=sqlite

before_script:
  # Composer
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
  - if [ "$DB" != 'agnostic' ]; then ./tests/bin/setup.$DB.sh; fi   # setup only for integration tests

script:
  - ./tests/bin/phpunit.$DB.sh;

matrix:
  exclude:
    - php: hhvm
      env: DB=pgsql DB_USER=postgres DB_NAME=postgres  # driver for PostgreSQL currently unsupported by HHVM, requires 3rd party dependency

#after_script:
#  - php vendor/bin/coveralls -v
